@startmindmap
* Home - Teamup Ventures
** Home - Teamup Ventures (/)
*** Link (View Details)
*** Pakistan’s First E-commerce Marketing tool launched by Pakistani Entrepreneur to make E-commerce more Competitive - Teamup Ventures (/scrapboard/pakistans-first-e-commerce-marketing-tool-launched-by-pakistani-entrepreneur-to-make-e-commerce-more-competitive)
**** Button: ×
**** Link (Terms & Conditions)
**** Terms & Conditions - Teamup Ventures (/terms-conditions)
***** Link (The Pakistan Story)
***** Pakistan Story - Teamup Ventures (/pakistan-story)
****** Button: ×
****** Link (Terms & Conditions)
****** Link (The Pakistan Story)
***** Link (Terms & Conditions)
***** Button: ×
**** Link (The Pakistan Story)
*** Button: ×
*** Link (View Details)
*** Startup challenges: the way out - Teamup Ventures (/scrapboard/startup-challenges-the-way-out)
**** Button: ×
**** Link (Terms & Conditions)
**** Link (The Pakistan Story)
*** Link (View Details)
*** The era of VCs and boom of start-ups - Teamup Ventures (/scrapboard/the-era-of-vcs-and-boom-of-start-ups)
**** Link (The Pakistan Story)
**** Button: ×
**** Link (Terms & Conditions)
*** Link (View Details)
*** Pakistan’s Sehat Kahani raises $1 million Pre-Series A to grow its telemedicine network - Teamup Ventures (/scrapboard/pakistans-sehat-kahani-raises-1-million-pre-series-a-to-grow-its-telemedicine-network)
**** Link (The Pakistan Story)
**** Link (Terms & Conditions)
**** Button: ×
*** Link (View Details)
*** Pakistan’s Truck It In raises $1.5 million pre-seed for its trucking marketplace - Teamup Ventures (/scrapboard/pakistans-truck-it-in-raises-1-5-million-pre-seed-for-its-trucking-marketplace)
**** Link (Terms & Conditions)
**** Button: ×
**** Link (The Pakistan Story)
*** Link (View Details)
*** Exclusive: Pakistani fintech SadaPay raises $7.2 million in country’s largest seed round - Teamup Ventures (/scrapboard/exclusive-pakistani-fintech-sadapay-raises-7-2-million-in-countrys-largest-seed-round)
**** Link (The Pakistan Story)
**** Button: ×
**** Link (Terms & Conditions)
*** Link (The Pakistan Story)
*** Link (View Details)
*** Local startup is using AI to detect Covid-19 - Teamup Ventures (/scrapboard/local-startup-is-using-ai-to-detect-covid-19)
**** Link (The Pakistan Story)
**** Button: ×
**** Link (Terms & Conditions)
*** Link (View Details)
*** To survive Pakistan’s COVID pandemic, grocery stores go online - Teamup Ventures (/scrapboard/to-survive-pakistans-covid-pandemic-grocery-stores-go-online)
**** Link (Terms & Conditions)
**** Button: ×
**** Link (The Pakistan Story)
*** Link (View Details)
*** Pakistani fintech startup called PayPro receives a grant of Rs 7.4 million from USAID and SMEA - Teamup Ventures (/scrapboard/pakistani-fintech-startup-called-paypro-receives-a-grant-of-rs-7-4-million-from-usaid-and-smea)
**** Button: ×
**** Link (The Pakistan Story)
**** Link (Terms & Conditions)
*** Link (View Details)
*** Islamabad based startup called Shopsy introduces voice search for its customers - Teamup Ventures (/scrapboard/islamabad-based-startup-called-shopsy-introduces-voice-search-for-its-customers)
**** Link (Terms & Conditions)
**** Button: ×
**** Link (The Pakistan Story)
*** Link (View Details)
*** Clicky.pk attracts $700,000 in pre-series A funding round - Teamup Ventures (/scrapboard/clicky-pk-attracts-700000-in-pre-series-a-funding-round)
**** Button: ×
**** Link (Terms & Conditions)
**** Link (The Pakistan Story)
*** Link (READ MORE)
*** Link (View Details)
*** Pakistan launches growth funds for startups - Teamup Ventures (/scrapboard/pakistan-launches-growth-funds-for-startups)
**** Link (The Pakistan Story)
**** Link (Terms & Conditions)
**** Button: ×
*** Link (View Details)
*** Pakistani Edtech Startup ‘Edkasa’ raises $320,000 pre-seed by launching an exam prep app for students - Teamup Ventures (/scrapboard/pakistani-edtech-startup-edkasa-raises-320000-pre-seed-by-launching-an-exam-prep-app-for-students)
**** Button: ×
**** Link (Terms & Conditions)
**** Link (The Pakistan Story)
*** Link (Terms & Conditions)
*** Link (View Details)
*** For a successful startup ecosystem, Pakistan needs to learn to celebrate failure - Teamup Ventures (/scrapboard/for-a-successful-startup-ecosystem-pakistan-needs-to-learn-to-celebrate-failure)
**** Link (The Pakistan Story)
**** Link (Terms & Conditions)
**** Button: ×
*** Link (View Details)
*** HumWell Comes To Rescue, With An All-Inclusive Telehealth Service - Teamup Ventures (/scrapboard/humwell-comes-to-rescue-with-an-all-inclusive-telehealth-service)
**** Link (Terms & Conditions)
**** Button: ×
**** Link (The Pakistan Story)
*** Link (View Details)
*** Pak tech startup Remotebase raises $1.4 million led by Indus Valley Capital - Teamup Ventures (/scrapboard/pak-tech-startup-remotebase-raises-1-4-million-led-by-indus-valley-capital)
**** Button: ×
**** Link (The Pakistan Story)
**** Link (Terms & Conditions)
*** Link (View Details)
*** Bayfikr – a User-Friendly Fin-Tech app, Making Payments in Pakistan Easier for Overseas Pakistanis - Teamup Ventures (/scrapboard/bayfikr-a-user-friendly-fin-tech-app-making-payments-in-pakistan-easier-for-overseas-pakistanis)
**** Button: ×
**** Link (The Pakistan Story)
**** Link (Terms & Conditions)
*** Link (View Details)
*** Despite a pandemic, Pakistani startups had their best year yet with over $65 million in funding - Teamup Ventures (/scrapboard/despite-a-pandemic-pakistani-startups-had-their-best-year-yet-with-over-65-million-in-funding)
**** Button: ×
**** Link (Terms & Conditions)
**** Link (The Pakistan Story)
*** Link (View Details)
*** Pakistani Startups Break Records in 2020 Despite Global Economic Slowdown - Teamup Ventures (/scrapboard/pakistani-startups-break-records-in-2020-despite-global-economic-slowdown)
**** Link (The Pakistan Story)
**** Link (Terms & Conditions)
**** Button: ×
*** Link (View Details)
*** NIC Welcomes It’s 10th Cohort of Startups - Teamup Ventures (/scrapboard/nic-welcomes-its-10th-cohort-of-startups)
**** Link (Terms & Conditions)
**** Button: ×
**** Link (The Pakistan Story)
@endmindmap